Repository Rayoil20/MindHack-soen341project2023, pull requests merged in 2023-04, with the labels that each got.

#38 Job postings
  front-end/MindHack/build/favicon.ico
  front-end/MindHack/build/logo192.png
  front-end/MindHack/build/logo512.png
  front-end/MindHack/build/manifest.json
  front-end/MindHack/build/robots.txt
  front-end/MindHack/package-lock.json
  front-end/MindHack/package.json
  front-end/MindHack/src/App.jsx
  front-end/MindHack/src/components/Navbar.js
  front-end/MindHack/src/employer_posting.js
  front-end/MindHack/src/jobs.css
Labels: User Story, task, Frontend

#37 Admin profile manage
  front-end/MindHack/src/App.jsx
  front-end/MindHack/src/admin_profile_manage.js
  front-end/MindHack/src/components/Navbar.js
Labels: User Story, Frontend

#32 Upload cv
  .gitignore
  back-end/.env
  back-end/controllers/test.js
  back-end/package-lock.json
  back-end/package.json
  back-end/routes/authenticate.js
  back-end/routes/upload.js
  back-end/routes/user.js
  back-end/server.js
  back-end/uploads/8a2e48439f130280a66ef7205fbebe39
  back-end/uploads/8c4087d48d7ef3608bff568ae1ad9d6b
  back-end/uploads/a3f1a8b11d9b65e96d568cd24331ed77
  front-end/MindHack/package-lock.json
  front-end/MindHack/package.json
  front-end/MindHack/src/App.jsx
  front-end/MindHack/src/login.js
  front-end/MindHack/src/upload.js
  package-lock.json
Labels: User Story, task, Backend, Frontend

#44 Merging the Dev branch into the Main
  .gitignore
  back-end/.env
  back-end/Database/mongodb.js
  back-end/Database/userschema.js
  back-end/controllers/test.js
  back-end/db/conn.js
  back-end/package-lock.json
  back-end/package.json
  back-end/routes/authenticate.js
  back-end/routes/upload.js
  back-end/routes/user.js
  back-end/server.js
  back-end/uploads/8a2e48439f130280a66ef7205fbebe39
  back-end/uploads/8c4087d48d7ef3608bff568ae1ad9d6b
  back-end/uploads/a3f1a8b11d9b65e96d568cd24331ed77
  front-end/MindHack/build/asset-manifest.json
  front-end/MindHack/build/favicon.ico
  front-end/MindHack/build/index.html
  front-end/MindHack/build/logo192.png
  front-end/MindHack/build/logo512.png
  front-end/MindHack/build/manifest.json
  front-end/MindHack/build/robots.txt
  front-end/MindHack/build/static/css/main.e6c13ad2.css
  front-end/MindHack/build/static/css/main.e6c13ad2.css.map
  front-end/MindHack/build/static/js/main.77d299de.js
  front-end/MindHack/build/static/js/main.77d299de.js.LICENSE.txt
  front-end/MindHack/build/static/js/main.77d299de.js.map
  front-end/MindHack/build/static/js/main.d0fdbf79.js
  front-end/MindHack/build/static/js/main.d0fdbf79.js.LICENSE.txt
  front-end/MindHack/build/static/js/main.d0fdbf79.js.map
  front-end/MindHack/build/static/media/logo.6ce24c58023cc2f8fd88fe9d219db6c6.svg
  front-end/MindHack/package-lock.json
  front-end/MindHack/package.json
  front-end/MindHack/src/App.jsx
  front-end/MindHack/src/admin_profile_manage.js
  front-end/MindHack/src/components/Navbar.js
  front-end/MindHack/src/edit_profile.js
  front-end/MindHack/src/employer_posting.js
  front-end/MindHack/src/homepage.js
  front-end/MindHack/src/login.js
  front-end/MindHack/src/profile.js
  front-end/MindHack/src/upload.js
  package-lock.json
Labels: bug, task

#47 Fixing dev
  front-end/MindHack/src/App.jsx
  front-end/MindHack/src/SignupPage.css
  front-end/MindHack/src/employer_posting.js
  front-end/MindHack/src/jobs.css
  front-end/MindHack/src/jobs.js
  front-end/MindHack/src/login.js
  front-end/MindHack/src/signup.js
Labels: bug, task, Frontend

#48 Possible to login
  back-end/routes/authenticate.js
  front-end/MindHack/package-lock.json
  front-end/MindHack/package.json
  front-end/MindHack/src/components/Navbar.js
  front-end/MindHack/src/login.js
  front-end/MindHack/src/signup.js
Labels: User Story, Backend, Frontend

#51 Missing files for the back
  back-end/routes/jobs.js
  back-end/routes/user.js
  back-end/server.js
Labels: bug, Backend

#52 Backend for job posting linked to the front
  back-end/routes/jobs.js
  front-end/MindHack/src/components/Navbar.js
  front-end/MindHack/src/employer_posting.js
  front-end/MindHack/src/homepage.js
  front-end/MindHack/src/jobs.js
Labels: User Story, Backend, Frontend
